In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
%matplotlib inline
%config InlineBackend.figure_format='retina'
import collections
import copy
from scipy import stats
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['mathtext.fontset'] = 'dejavuserif'
rcParams['mathtext.rm'] = 'serif'
rcParams['mathtext.it'] = 'serif:italic'
rcParams['mathtext.bf'] = 'serif:bold'
rcParams['axes.titlepad'] = 12

In [2]:
import processing_functions as pf

In [3]:
reload(pf)

<module 'processing_functions' from 'processing_functions.pyc'>

In [4]:
covtot_19p0 = pf.calc_covariance((np.load('Run_102218/jk_19p0_x.npz')['jkcov']+np.load('Run_102218/jk_19p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_19p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_19p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_19p0.npz'))
cov_cut_19p0 = pf.cut_by_func_2D(covtot_19p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_19p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_19p0,rcond=1e-5)

covtot_19p5 = pf.calc_covariance((np.load('Run_102218/jk_19p5_x.npz')['jkcov']+np.load('Run_102218/jk_19p5_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_19p5_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_19p5.npz')['func'],\
                             np.load('Run_102218/fidrandom_19p5.npz'))
cov_cut_19p5 = pf.cut_by_func_2D(covtot_19p5,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_19p5 = pf.apply_to_dict(pf.inv_cov,cov_cut_19p5,rcond=1e-5)

covtot_20p0 = pf.calc_covariance((np.load('Run_102218/jk_20p0_x.npz')['jkcov']+np.load('Run_102218/jk_20p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_20p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_20p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_20p0.npz'))
cov_cut_20p0 = pf.cut_by_func_2D(covtot_20p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_20p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_20p0,rcond=1e-5)

covtot_20p5 = pf.calc_covariance((np.load('Run_102218/jk_20p5_x.npz')['jkcov']+np.load('Run_102218/jk_20p5_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_20p5_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_20p5.npz')['func'],\
                             np.load('Run_102218/fidrandom_20p5.npz'))
cov_cut_20p5 = pf.cut_by_func_2D(covtot_20p5,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
invcov_cut_20p5 = pf.apply_to_dict(pf.inv_cov,cov_cut_20p5,rcond=1e-5)

covtot_21p0 = pf.calc_covariance((np.load('Run_102218/jk_21p0_x.npz')['jkcov']+np.load('Run_102218/jk_21p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_21p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_21p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_21p0.npz'))
cov_cut_21p0 = pf.cut_by_func_2D(covtot_21p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})
invcov_cut_21p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_21p0,rcond=1e-5)

In [5]:
pertfunc_dict_19p0,pertparam_19p0 = pf.load_pert('-19.0')
trim_mean_curves_19p0 = pf.trimmean_of_dict(pertfunc_dict_19p0)
func_cut_tm_19p0 = pf.cut_by_func_1D(trim_mean_curves_19p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_19p5,pertparam_19p5 = pf.load_pert('-19.5')
trim_mean_curves_19p5 = pf.trimmean_of_dict(pertfunc_dict_19p5)
func_cut_tm_19p5 = pf.cut_by_func_1D(trim_mean_curves_19p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_20p0,pertparam_20p0 = pf.load_pert('-20.0')
trim_mean_curves_20p0 = pf.trimmean_of_dict(pertfunc_dict_20p0)
func_cut_tm_20p0 = pf.cut_by_func_1D(trim_mean_curves_20p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_20p5,pertparam_20p5 = pf.load_pert('-20.5')
trim_mean_curves_20p5 = pf.trimmean_of_dict(pertfunc_dict_20p5)
func_cut_tm_20p5 = pf.cut_by_func_1D(trim_mean_curves_20p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
pertfunc_dict_21p0,pertparam_21p0 = pf.load_pert('-21.0')
trim_mean_curves_21p0 = pf.trimmean_of_dict(pertfunc_dict_21p0)
func_cut_tm_21p0 = pf.cut_by_func_1D(trim_mean_curves_21p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})

In [6]:
gcv_alphas_tm_19p0 = pf.gcv_alphas(trim_mean_curves_19p0,pertparam_19p0)
gcv_alphas_cut_tm_19p0 = pf.cut_by_func_1D(gcv_alphas_tm_19p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_19p5 = pf.gcv_alphas(trim_mean_curves_19p5,pertparam_19p5)
gcv_alphas_cut_tm_19p5 = pf.cut_by_func_1D(gcv_alphas_tm_19p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_20p0 = pf.gcv_alphas(trim_mean_curves_20p0,pertparam_20p0)
gcv_alphas_cut_tm_20p0 = pf.cut_by_func_1D(gcv_alphas_tm_20p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_20p5 = pf.gcv_alphas(trim_mean_curves_20p5,pertparam_20p5)
gcv_alphas_cut_tm_20p5 = pf.cut_by_func_1D(gcv_alphas_tm_20p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
gcv_alphas_tm_21p0 = pf.gcv_alphas(trim_mean_curves_21p0,pertparam_21p0)
gcv_alphas_cut_tm_21p0 = pf.cut_by_func_1D(gcv_alphas_tm_21p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})

In [7]:
def iterate_smooth(func_cut, gcv_alphas_cut, invcov_cut, pertparam, oneside, p0, combkey, amin, maxiter=5):  #for each combination separately
    it = 0
    iter_sigma = []
    iter_sigma.append(np.zeros(6))
    f = func_cut[combkey]
    alphas = np.ones((6,f.shape[1]))
    while it<maxiter:
        it += 1
        alphas = np.maximum(gcv_alphas_cut[combkey],alphas)
        alphas = np.maximum(alphas,(amin*np.ones((f.shape[1],6))).T)
        alphas = np.minimum(np.ones((6,f.shape[1])),alphas)
        dfdp = pf.locfit_comb(f,alphas,pertparam,p0)
        fisher = pf.calc_fisher(dfdp,invcov_cut[combkey])
        sigma = pf.calc_1sigma(fisher)
        iter_sigma.append(sigma)
        if np.all(iter_sigma[-2]<1.2*sigma) and np.all(iter_sigma[-2]>sigma/1.2):
            break
        if it<maxiter-1:
            alphas = (np.ones((f.shape[1],6))*pf.sigma_to_alpha(sigma,oneside)).T
    sigma_u = 1./np.sqrt(fisher.diagonal())
    return iter_sigma[-1], sigma_u, fisher, dfdp, alphas

In [8]:
klist_all = ['w','d','v','c','a','r',                                      # 0-5
         'wd','wv','wc','wa','wr',                                         # 6-10
         'dv','dc','da','dr',                                              # 11-14
         'vc','va','vr',                                                   # 15-17
         'ca','cr','ar',                                                   # 18-20
         'wdv','wdc','wda','wdr','wvc','wva','wvr','wca','wcr','war',      # 21-30
         'dvc','dva','dvr','dca','dcr','dar',                              # 31-36
         'vca','vcr','var','car',                                          # 37-40
         'wdvc','wdva','wdvr','wdca','wdcr','wdar',                        # 41-46
         'wvca','wvcr','wvar','wcar',                                      # 47-50
         'dvca','dvcr','dvar','dcar','vcar',                               # 51-55
         'wdvca','wdvcr','wdvar','wdcar','wvcar','dvcar',                  # 56-61
         'wdvcar']                                                         # 62

In [9]:
sigma_tm_19p0 = {}
sigma_u_tm_19p0 = {}
fisher_tm_19p0 = {}
dfdp_tm_19p0 = {}
alphas_tm_19p0 = {}
for k in klist_all:
    sigma_tm_19p0[k], sigma_u_tm_19p0[k], fisher_tm_19p0[k], dfdp_tm_19p0[k], alphas_tm_19p0[k] = \
    iterate_smooth(func_cut_tm_19p0,gcv_alphas_cut_tm_19p0,invcov_cut_19p0,pertparam_19p0,\
                   pf.oneside_ranges[0],pf.p19p0,k,np.array((0,0,0.25,0,0.5,0.25)))

In [11]:
sigma_tm_19p5 = {}
sigma_u_tm_19p5 = {}
fisher_tm_19p5 = {}
dfdp_tm_19p5 = {}
alphas_tm_19p5 = {}
for k in klist_all:
    sigma_tm_19p5[k], sigma_u_tm_19p5[k], fisher_tm_19p5[k], dfdp_tm_19p5[k], alphas_tm_19p5[k] = \
    iterate_smooth(func_cut_tm_19p5,gcv_alphas_cut_tm_19p5,invcov_cut_19p5,pertparam_19p5,\
                   pf.oneside_ranges[1],pf.p19p5,k,np.array((0.35,0,0.4,0.15,0.5,0.35)))

In [12]:
sigma_tm_20p0 = {}
sigma_u_tm_20p0 = {}
fisher_tm_20p0 = {}
dfdp_tm_20p0 = {}
alphas_tm_20p0 = {}
for k in klist_all:
    sigma_tm_20p0[k], sigma_u_tm_20p0[k], fisher_tm_20p0[k], dfdp_tm_20p0[k], alphas_tm_20p0[k] = \
    iterate_smooth(func_cut_tm_20p0,gcv_alphas_cut_tm_20p0,invcov_cut_20p0,pertparam_20p0,\
                   pf.oneside_ranges[2],pf.p20p0,k,np.array((0.35,0,0.45,0.25,0.5,0.4)))

In [13]:
sigma_tm_20p5 = {}
sigma_u_tm_20p5 = {}
fisher_tm_20p5 = {}
dfdp_tm_20p5 = {}
alphas_tm_20p5 = {}
for k in klist_all:
    sigma_tm_20p5[k], sigma_u_tm_20p5[k], fisher_tm_20p5[k], dfdp_tm_20p5[k], alphas_tm_20p5[k] = \
    iterate_smooth(func_cut_tm_20p5,gcv_alphas_cut_tm_20p5,invcov_cut_20p5,pertparam_20p5,\
                   pf.oneside_ranges[3],pf.p20p5,k,np.array((0.5,0,0.8,0.15,0.75,0.5)))

In [14]:
sigma_tm_21p0 = {}
sigma_u_tm_21p0 = {}
fisher_tm_21p0 = {}
dfdp_tm_21p0 = {}
alphas_tm_21p0 = {}
for k in klist_all:
    sigma_tm_21p0[k], sigma_u_tm_21p0[k], fisher_tm_21p0[k], dfdp_tm_21p0[k], alphas_tm_21p0[k] = \
    iterate_smooth(func_cut_tm_21p0,gcv_alphas_cut_tm_21p0,invcov_cut_21p0,pertparam_21p0,\
                   pf.oneside_ranges[4],pf.p21p0,k,np.array((0.7,0,0.9,0.2,0.9,0.75)))

In [21]:
for k in klist_all:
    print k
    print sigma_tm_19p0[k]
    print sigma_tm_19p5[k]
    print sigma_tm_20p0[k]
    print sigma_tm_20p5[k]
    print sigma_tm_21p0[k]

w
[ 0.03024918  0.03838117  0.57735777  0.2657666   0.56870978  0.2533663 ]
[ 0.02292111  0.02510273  0.49513056  0.2118131   0.47592863  0.24956205]
[ 0.02401196  0.02311345  0.4095334   0.14885968  0.59299031  0.34841986]
[ 0.03051568  0.02230926  0.20908314  0.04152192  0.8708031   0.49410252]
[ 0.08342128  0.02977503  0.26902809  0.16783297  0.75346011  0.80211463]
d
[ 0.05703156  0.07374487  0.14462059  0.08709657  0.71111859  0.26913892]
[ 0.07154844  0.07219994  0.12668156  0.06763383  0.70024892  0.27619713]
[ 0.0723973   0.06050505  0.13684039  0.05864602  0.83400128  0.35590339]
[ 0.08982331  0.05203572  0.19152739  0.04697619  1.00120121  0.45826605]
[ 0.22561653  0.06649874  0.09983627  0.07842307  0.67215725  0.76365325]
v
[ 0.68997124  0.37211398  0.12346783  0.21544336  0.60376614  3.84784146]
[ 0.67018267  0.30318879  0.18026156  0.13306112  0.60531379  3.10457892]
[ 0.80875689  0.22002185  0.15307556  0.10385164  0.56075201  2.81013085]
[ 1.06710749  0.11277407  0.1193

In [22]:
sigma_tm_19p0['wd']>sigma_tm_19p0['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [23]:
sigma_tm_19p5['wd']>sigma_tm_19p5['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [24]:
sigma_tm_20p0['wd']>sigma_tm_20p0['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [25]:
sigma_tm_20p5['wd']>sigma_tm_20p5['wc']

array([ True,  True, False, False,  True,  True], dtype=bool)

In [26]:
sigma_tm_21p0['wd']>sigma_tm_21p0['wc']

array([ True,  True, False, False, False,  True], dtype=bool)