In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
%matplotlib inline
%config InlineBackend.figure_format='retina'
import collections
import copy
from scipy import stats
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['mathtext.fontset'] = 'dejavuserif'
rcParams['mathtext.rm'] = 'serif'
rcParams['mathtext.it'] = 'serif:italic'
rcParams['mathtext.bf'] = 'serif:bold'
rcParams['axes.titlepad'] = 12

In [2]:
import processing_functions as pf

In [3]:
reload(pf)

<module 'processing_functions' from 'processing_functions.pyc'>

In [4]:
covtot_19p0 = pf.calc_covariance((np.load('Run_102218/jk_19p0_x.npz')['jkcov']+np.load('Run_102218/jk_19p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_19p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_19p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_19p0.npz'))
cov_cut_19p0 = pf.cut_by_func_2D(covtot_19p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_19p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_19p0,rcond=1e-5)

covtot_19p5 = pf.calc_covariance((np.load('Run_102218/jk_19p5_x.npz')['jkcov']+np.load('Run_102218/jk_19p5_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_19p5_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_19p5.npz')['func'],\
                             np.load('Run_102218/fidrandom_19p5.npz'))
cov_cut_19p5 = pf.cut_by_func_2D(covtot_19p5,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_19p5 = pf.apply_to_dict(pf.inv_cov,cov_cut_19p5,rcond=1e-5)

covtot_20p0 = pf.calc_covariance((np.load('Run_102218/jk_20p0_x.npz')['jkcov']+np.load('Run_102218/jk_20p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_20p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_20p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_20p0.npz'))
cov_cut_20p0 = pf.cut_by_func_2D(covtot_20p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
invcov_cut_20p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_20p0,rcond=1e-5)

covtot_20p5 = pf.calc_covariance((np.load('Run_102218/jk_20p5_x.npz')['jkcov']+np.load('Run_102218/jk_20p5_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_20p5_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_20p5.npz')['func'],\
                             np.load('Run_102218/fidrandom_20p5.npz'))
cov_cut_20p5 = pf.cut_by_func_2D(covtot_20p5,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
invcov_cut_20p5 = pf.apply_to_dict(pf.inv_cov,cov_cut_20p5,rcond=1e-5)

covtot_21p0 = pf.calc_covariance((np.load('Run_102218/jk_21p0_x.npz')['jkcov']+np.load('Run_102218/jk_21p0_y.npz')['jkcov']\
                             +np.load('Run_102218/jk_21p0_z.npz')['jkcov'])/3.,\
                             np.load('Run_102218/fidreal_21p0.npz')['func'],\
                             np.load('Run_102218/fidrandom_21p0.npz'))
cov_cut_21p0 = pf.cut_by_func_2D(covtot_21p0,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})
invcov_cut_21p0 = pf.apply_to_dict(pf.inv_cov,cov_cut_21p0,rcond=1e-5)

In [5]:
pertfunc_dict_19p0,pertparam_19p0 = pf.load_pert('-19.0')
trim_mean_curves_19p0 = pf.trimmean_of_dict(pertfunc_dict_19p0)
func_cut_tm_19p0 = pf.cut_by_func_1D(trim_mean_curves_19p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_19p5,pertparam_19p5 = pf.load_pert('-19.5')
trim_mean_curves_19p5 = pf.trimmean_of_dict(pertfunc_dict_19p5)
func_cut_tm_19p5 = pf.cut_by_func_1D(trim_mean_curves_19p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_20p0,pertparam_20p0 = pf.load_pert('-20.0')
trim_mean_curves_20p0 = pf.trimmean_of_dict(pertfunc_dict_20p0)
func_cut_tm_20p0 = pf.cut_by_func_1D(trim_mean_curves_20p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
pertfunc_dict_20p5,pertparam_20p5 = pf.load_pert('-20.5')
trim_mean_curves_20p5 = pf.trimmean_of_dict(pertfunc_dict_20p5)
func_cut_tm_20p5 = pf.cut_by_func_1D(trim_mean_curves_20p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
pertfunc_dict_21p0,pertparam_21p0 = pf.load_pert('-21.0')
trim_mean_curves_21p0 = pf.trimmean_of_dict(pertfunc_dict_21p0)
func_cut_tm_21p0 = pf.cut_by_func_1D(trim_mean_curves_21p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})

In [6]:
gcv_alphas_tm_19p0 = pf.gcv_alphas(trim_mean_curves_19p0,pertparam_19p0)
gcv_alphas_cut_tm_19p0 = pf.cut_by_func_1D(gcv_alphas_tm_19p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_19p5 = pf.gcv_alphas(trim_mean_curves_19p5,pertparam_19p5)
gcv_alphas_cut_tm_19p5 = pf.cut_by_func_1D(gcv_alphas_tm_19p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_20p0 = pf.gcv_alphas(trim_mean_curves_20p0,pertparam_20p0)
gcv_alphas_cut_tm_20p0 = pf.cut_by_func_1D(gcv_alphas_tm_20p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,120),'a':range(120,150),'r':range(150,180)})
gcv_alphas_tm_20p5 = pf.gcv_alphas(trim_mean_curves_20p5,pertparam_20p5)
gcv_alphas_cut_tm_20p5 = pf.cut_by_func_1D(gcv_alphas_tm_20p5,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,116),'a':range(120,146),'r':range(150,180)})
gcv_alphas_tm_21p0 = pf.gcv_alphas(trim_mean_curves_21p0,pertparam_21p0)
gcv_alphas_cut_tm_21p0 = pf.cut_by_func_1D(gcv_alphas_tm_21p0,axis=1,funcidx={'w':range(1,30),'d':range(30,60),'v':range(60,90),\
                                           'c':range(90,111),'a':range(120,142),'r':range(150,180)})

In [7]:
def iterate_smooth(func_cut, gcv_alphas_cut, invcov_cut, pertparam, oneside, p0, combkey, amin, maxiter=5):  #for each combination separately
    it = 0
    iter_sigma = []
    iter_sigma.append(np.zeros(6))
    f = func_cut[combkey]
    alphas = np.ones((6,f.shape[1]))
    while it<maxiter:
        it += 1
        alphas = np.maximum(gcv_alphas_cut[combkey],alphas)
        alphas = np.maximum(alphas,(amin*np.ones((f.shape[1],6))).T)
        alphas = np.minimum(np.ones((6,f.shape[1])),alphas)
        dfdp = pf.locfit_comb(f,alphas,pertparam,p0)
        fisher = pf.calc_fisher(dfdp,invcov_cut[combkey])
        sigma = pf.calc_1sigma(fisher)
        iter_sigma.append(sigma)
        if np.all(iter_sigma[-2]<1.2*sigma) and np.all(iter_sigma[-2]>sigma/1.2):
            break
        if it<maxiter-1:
            alphas = (np.ones((f.shape[1],6))*pf.sigma_to_alpha(sigma,oneside)).T
    sigma_u = 1./np.sqrt(fisher.diagonal())
    return iter_sigma[-1], sigma_u, fisher, dfdp, alphas

In [8]:
klist_all = ['w','d','v','c','a','r',                                      # 0-5
         'wd','wv','wc','wa','wr',                                         # 6-10
         'dv','dc','da','dr',                                              # 11-14
         'vc','va','vr',                                                   # 15-17
         'ca','cr','ar',                                                   # 18-20
         'wdv','wdc','wda','wdr','wvc','wva','wvr','wca','wcr','war',      # 21-30
         'dvc','dva','dvr','dca','dcr','dar',                              # 31-36
         'vca','vcr','var','car',                                          # 37-40
         'wdvc','wdva','wdvr','wdca','wdcr','wdar',                        # 41-46
         'wvca','wvcr','wvar','wcar',                                      # 47-50
         'dvca','dvcr','dvar','dcar','vcar',                               # 51-55
         'wdvca','wdvcr','wdvar','wdcar','wvcar','dvcar',                  # 56-61
         'wdvcar']                                                         # 62

In [9]:
sigma_tm_19p0 = {}
sigma_u_tm_19p0 = {}
fisher_tm_19p0 = {}
dfdp_tm_19p0 = {}
alphas_tm_19p0 = {}
for k in klist_all:
    sigma_tm_19p0[k], sigma_u_tm_19p0[k], fisher_tm_19p0[k], dfdp_tm_19p0[k], alphas_tm_19p0[k] = \
    iterate_smooth(func_cut_tm_19p0,gcv_alphas_cut_tm_19p0,invcov_cut_19p0,pertparam_19p0,\
                   pf.oneside_ranges[0],pf.p19p0,k,np.array((0,0,0.25,0,0.5,0.25)))

In [10]:
sigma_tm_19p5 = {}
sigma_u_tm_19p5 = {}
fisher_tm_19p5 = {}
dfdp_tm_19p5 = {}
alphas_tm_19p5 = {}
for k in klist_all:
    sigma_tm_19p5[k], sigma_u_tm_19p5[k], fisher_tm_19p5[k], dfdp_tm_19p5[k], alphas_tm_19p5[k] = \
    iterate_smooth(func_cut_tm_19p5,gcv_alphas_cut_tm_19p5,invcov_cut_19p5,pertparam_19p5,\
                   pf.oneside_ranges[1],pf.p19p5,k,np.array((0.35,0,0.4,0.15,0.5,0.35)))

In [11]:
sigma_tm_20p0 = {}
sigma_u_tm_20p0 = {}
fisher_tm_20p0 = {}
dfdp_tm_20p0 = {}
alphas_tm_20p0 = {}
for k in klist_all:
    sigma_tm_20p0[k], sigma_u_tm_20p0[k], fisher_tm_20p0[k], dfdp_tm_20p0[k], alphas_tm_20p0[k] = \
    iterate_smooth(func_cut_tm_20p0,gcv_alphas_cut_tm_20p0,invcov_cut_20p0,pertparam_20p0,\
                   pf.oneside_ranges[2],pf.p20p0,k,np.array((0.35,0,0.45,0.25,0.5,0.4)))

In [12]:
sigma_tm_20p5 = {}
sigma_u_tm_20p5 = {}
fisher_tm_20p5 = {}
dfdp_tm_20p5 = {}
alphas_tm_20p5 = {}
for k in klist_all:
    sigma_tm_20p5[k], sigma_u_tm_20p5[k], fisher_tm_20p5[k], dfdp_tm_20p5[k], alphas_tm_20p5[k] = \
    iterate_smooth(func_cut_tm_20p5,gcv_alphas_cut_tm_20p5,invcov_cut_20p5,pertparam_20p5,\
                   pf.oneside_ranges[3],pf.p20p5,k,np.array((0.5,0,0.8,0.15,0.75,0.5)))

In [13]:
sigma_tm_21p0 = {}
sigma_u_tm_21p0 = {}
fisher_tm_21p0 = {}
dfdp_tm_21p0 = {}
alphas_tm_21p0 = {}
for k in klist_all:
    sigma_tm_21p0[k], sigma_u_tm_21p0[k], fisher_tm_21p0[k], dfdp_tm_21p0[k], alphas_tm_21p0[k] = \
    iterate_smooth(func_cut_tm_21p0,gcv_alphas_cut_tm_21p0,invcov_cut_21p0,pertparam_21p0,\
                   pf.oneside_ranges[4],pf.p21p0,k,np.array((0.7,0,0.9,0.2,0.9,0.75)))

In [14]:
for k in klist_all:
    print k
    print sigma_tm_19p0[k]
    print sigma_tm_19p5[k]
    print sigma_tm_20p0[k]
    print sigma_tm_20p5[k]
    print sigma_tm_21p0[k]

w
[ 0.03833738  0.04873298  0.64520596  0.2984152   0.71240356  0.33516043]
[ 0.02870583  0.03162573  0.55753916  0.23827675  0.626396    0.34638835]
[ 0.03086557  0.02877754  0.47491126  0.1725932   0.77559798  0.44787631]
[ 0.03817632  0.02677566  0.24384359  0.04920797  1.06775267  0.60178295]
[ 0.09657736  0.03260172  0.30767698  0.1909896   0.84163353  0.90214244]
d
[ 0.06630991  0.08538879  0.15703882  0.09599236  0.79210543  0.31861034]
[ 0.07991425  0.08018679  0.138032    0.07382514  0.76270518  0.32878408]
[ 0.08058385  0.06691951  0.1485424   0.06188621  0.8613567   0.42599392]
[ 0.0982221   0.05737397  0.19707453  0.04796532  1.05314242  0.52019837]
[ 0.2281377   0.07086218  0.10054968  0.07826568  0.66931075  0.80743299]
v
[ 0.68889178  0.37428331  0.12856896  0.21683491  0.6267992   3.9899192 ]
[ 0.65723939  0.2954234   0.17882808  0.12989225  0.61684462  3.10196961]
[ 0.78268963  0.21204168  0.15452468  0.10242476  0.56218626  2.73402178]
[ 1.02301209  0.10877778  0.1171

In [15]:
sigma_tm_19p0['wd']>sigma_tm_19p0['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [16]:
sigma_tm_19p5['wd']>sigma_tm_19p5['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [17]:
sigma_tm_20p0['wd']>sigma_tm_20p0['wc']

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [18]:
sigma_tm_20p5['wd']>sigma_tm_20p5['wc']

array([ True,  True, False, False,  True,  True], dtype=bool)

In [19]:
sigma_tm_21p0['wd']>sigma_tm_21p0['wc']

array([ True,  True, False, False, False,  True], dtype=bool)

In [28]:
for k in klist_all[:21]:
    #print k
    print np.round(sigma_tm_19p0[k][3],2),np.round(sigma_tm_19p0[k][2],3),\
    np.round(sigma_tm_19p0[k][0],3),np.round(sigma_tm_19p0[k][1],2),\
    np.round(sigma_tm_19p0[k][4],2),np.round(sigma_tm_19p0[k][5],2)
k = 'wdvcar'
print np.round(sigma_tm_19p0[k][3],2),np.round(sigma_tm_19p0[k][2],3),\
    np.round(sigma_tm_19p0[k][0],3),np.round(sigma_tm_19p0[k][1],2),\
    np.round(sigma_tm_19p0[k][4],2),np.round(sigma_tm_19p0[k][5],2)

0.3 0.645 0.038 0.05 0.71 0.34
0.1 0.157 0.066 0.09 0.79 0.32
0.22 0.129 0.689 0.37 0.63 3.99
0.18 0.179 0.091 0.18 1.34 0.2
0.06 0.151 0.049 0.07 0.46 0.36
0.05 0.073 0.04 0.06 0.57 0.21
0.06 0.121 0.016 0.02 0.41 0.2
0.05 0.086 0.019 0.03 0.31 0.25
0.03 0.048 0.013 0.02 0.15 0.15
0.05 0.111 0.014 0.02 0.16 0.19
0.03 0.062 0.013 0.02 0.27 0.15
0.06 0.084 0.036 0.04 0.31 0.19
0.04 0.054 0.022 0.03 0.19 0.12
0.05 0.082 0.03 0.03 0.17 0.19
0.04 0.064 0.022 0.03 0.29 0.14
0.05 0.057 0.03 0.06 0.43 0.19
0.05 0.061 0.046 0.04 0.23 0.35
0.03 0.05 0.03 0.04 0.38 0.2
0.04 0.055 0.017 0.03 0.24 0.14
0.04 0.054 0.019 0.03 0.23 0.13
0.03 0.056 0.023 0.03 0.23 0.17
0.02 0.031 0.009 0.01 0.1 0.07


In [ ]:
$\wprp$ & 0.30 & 0.645 & 0.038 & 0.05 & 0.71 & 0.34 \\
$\Dsigma$ & 0.10 & 0.157 & 0.066 & 0.09 & 0.79 & 0.32 \\
$\VPF$ & 0.22 & 0.129 & 0.689 & 0.37 & 0.63 & 3.99 \\
$\Pncic$ & 0.18 & 0.179 & 0.091 & 0.18 & 1.34 & 0.20 \\
$\Pncia$ & 0.06 & 0.151 & 0.049 & 0.07 & 0.46 & 0.36 \\
$\Pratio$ & 0.05 & 0.073 & 0.040 & 0.06 & 0.57 & 0.21 \\
$\wprp+\Dsigma$ & 0.06 & 0.121 & 0.016 & 0.02 & 0.41 & 0.20 \\
$\wprp+\VPF$ & 0.05 & 0.086 & 0.019 & 0.03 & 0.31 & 0.25 \\
$\wprp+\Pncic$ & 0.03 & 0.048 & 0.013 & 0.02 & 0.15 & 0.15 \\
$\wprp+\Pncia$ & 0.05 & 0.111 & 0.014 & 0.02 & 0.16 & 0.19 \\
$\wprp+\Pratio$ & 0.03 & 0.062 & 0.013 & 0.02 & 0.27 & 0.15 \\
$\Dsigma+\VPF$ & 0.06 & 0.084 & 0.036 & 0.04 & 0.31 & 0.19 \\
$\Dsigma+\Pncic$ & 0.04 & 0.054 & 0.022 & 0.03 & 0.19 & 0.12 \\
$\Dsigma+\Pncia$ & 0.05 & 0.082 & 0.030 & 0.03 & 0.17 & 0.19 \\
$\Dsigma+\Pratio$ & 0.04 & 0.064 & 0.022 & 0.03 & 0.29 & 0.14 \\
$\VPF+\Pncic$ & 0.05 & 0.057 & 0.030 & 0.06 & 0.43 & 0.19 \\
$\VPF+\Pncia$ & 0.05 & 0.061 & 0.046 & 0.04 & 0.23 & 0.35 \\
$\VPF+\Pratio$ & 0.03 & 0.050 & 0.030 & 0.04 & 0.38 & 0.20 \\
$\Pncic+\Pncia$ & 0.04 & 0.055 & 0.017 & 0.03 & 0.24 & 0.14 \\
$\Pncic+\Pratio$ & 0.04 & 0.054 & 0.019 & 0.03 & 0.23 & 0.13 \\
$\Pncia+\Pratio$ & 0.03 & 0.056 & 0.023 & 0.03 & 0.23 & 0.17 \\

In [29]:
for k in klist_all[:21]:
    #print k
    print np.round(sigma_tm_19p5[k][3],2),np.round(sigma_tm_19p5[k][2],3),\
    np.round(sigma_tm_19p5[k][0],3),np.round(sigma_tm_19p5[k][1],2),\
    np.round(sigma_tm_19p5[k][4],2),np.round(sigma_tm_19p5[k][5],2)
k = 'wdvcar'
print np.round(sigma_tm_19p5[k][3],2),np.round(sigma_tm_19p5[k][2],3),\
    np.round(sigma_tm_19p5[k][0],3),np.round(sigma_tm_19p5[k][1],2),\
    np.round(sigma_tm_19p5[k][4],2),np.round(sigma_tm_19p5[k][5],2)

0.24 0.558 0.029 0.03 0.63 0.35
0.07 0.138 0.08 0.08 0.76 0.33
0.13 0.179 0.657 0.3 0.62 3.1
0.09 0.119 0.088 0.14 1.06 0.16
0.05 0.141 0.075 0.11 0.72 0.37
0.04 0.076 0.052 0.05 0.58 0.28
0.05 0.104 0.022 0.02 0.4 0.23
0.04 0.077 0.021 0.02 0.32 0.27
0.02 0.046 0.016 0.02 0.17 0.12
0.04 0.091 0.018 0.02 0.18 0.22
0.03 0.057 0.017 0.02 0.31 0.17
0.05 0.079 0.047 0.04 0.3 0.21
0.03 0.05 0.026 0.03 0.2 0.12
0.04 0.071 0.038 0.03 0.21 0.21
0.03 0.06 0.028 0.03 0.31 0.16
0.04 0.052 0.039 0.06 0.44 0.14
0.04 0.058 0.062 0.04 0.26 0.35
0.03 0.052 0.038 0.04 0.34 0.27
0.03 0.052 0.023 0.03 0.27 0.12
0.03 0.052 0.025 0.03 0.26 0.13
0.03 0.054 0.032 0.03 0.26 0.22
0.01 0.03 0.012 0.01 0.11 0.07


In [ ]:
$\wprp$   & 0.24 & 0.558 & 0.029 & 0.03 & 0.63 & 0.35 \\
$\Dsigma$ & 0.07 & 0.138 & 0.080 & 0.08 & 0.76 & 0.33 \\
$\VPF$    & 0.13 & 0.179 & 0.657 & 0.30 & 0.62 & 3.10 \\
$\Pncic$  & 0.09 & 0.119 & 0.088 & 0.14 & 1.06 & 0.16 \\
$\Pncia$  & 0.05 & 0.141 & 0.075 & 0.11 & 0.72 & 0.37 \\
$\Pratio$ & 0.04 & 0.076 & 0.052 & 0.05 & 0.58 & 0.28 \\
$\wprp+\Dsigma$   & 0.05 & 0.104 & 0.022 & 0.02 & 0.40 & 0.23 \\
$\wprp+\VPF$      & 0.04 & 0.077 & 0.021 & 0.02 & 0.32 & 0.27 \\
$\wprp+\Pncic$    & 0.02 & 0.046 & 0.016 & 0.02 & 0.17 & 0.12 \\
$\wprp+\Pncia$    & 0.04 & 0.091 & 0.018 & 0.02 & 0.18 & 0.22 \\
$\wprp+\Pratio$   & 0.03 & 0.057 & 0.017 & 0.02 & 0.31 & 0.17 \\
$\Dsigma+\VPF$    & 0.05 & 0.079 & 0.047 & 0.04 & 0.30 & 0.21 \\
$\Dsigma+\Pncic$  & 0.03 & 0.050 & 0.026 & 0.03 & 0.20 & 0.12 \\
$\Dsigma+\Pncia$  & 0.04 & 0.071 & 0.038 & 0.03 & 0.21 & 0.21 \\
$\Dsigma+\Pratio$ & 0.03 & 0.060 & 0.028 & 0.03 & 0.31 & 0.16 \\
$\VPF+\Pncic$     & 0.04 & 0.052 & 0.039 & 0.06 & 0.44 & 0.14 \\
$\VPF+\Pncia$     & 0.04 & 0.058 & 0.062 & 0.04 & 0.26 & 0.35 \\
$\VPF+\Pratio$    & 0.03 & 0.052 & 0.038 & 0.04 & 0.34 & 0.27 \\
$\Pncic+\Pncia$   & 0.03 & 0.052 & 0.023 & 0.03 & 0.27 & 0.12 \\
$\Pncic+\Pratio$  & 0.03 & 0.052 & 0.025 & 0.03 & 0.26 & 0.13 \\
$\Pncia+\Pratio$  & 0.03 & 0.054 & 0.032 & 0.03 & 0.26 & 0.22 \\
$\wprp+\Dsigma+\VPF+\Pncic+\Pncia+\Pratio$ & 0.01 & 0.030 & 0.012 & 0.01 & 0.11 & 0.07 \\

In [30]:
for k in klist_all[:21]:
    #print k
    print np.round(sigma_tm_20p0[k][3],2),np.round(sigma_tm_20p0[k][2],3),\
    np.round(sigma_tm_20p0[k][0],3),np.round(sigma_tm_20p0[k][1],2),\
    np.round(sigma_tm_20p0[k][4],2),np.round(sigma_tm_20p0[k][5],2)
k = 'wdvcar'
print np.round(sigma_tm_20p0[k][3],2),np.round(sigma_tm_20p0[k][2],3),\
    np.round(sigma_tm_20p0[k][0],3),np.round(sigma_tm_20p0[k][1],2),\
    np.round(sigma_tm_20p0[k][4],2),np.round(sigma_tm_20p0[k][5],2)

0.17 0.475 0.031 0.03 0.78 0.45
0.06 0.149 0.081 0.07 0.86 0.43
0.1 0.155 0.783 0.21 0.56 2.73
0.09 0.157 0.081 0.11 1.32 0.16
0.04 0.137 0.088 0.11 0.91 0.33
0.05 0.112 0.064 0.05 0.8 0.32
0.05 0.123 0.024 0.02 0.53 0.29
0.03 0.082 0.024 0.02 0.39 0.32
0.03 0.062 0.02 0.01 0.25 0.12
0.04 0.1 0.021 0.02 0.26 0.22
0.03 0.069 0.021 0.02 0.41 0.19
0.04 0.083 0.054 0.04 0.39 0.25
0.03 0.065 0.031 0.02 0.3 0.12
0.03 0.076 0.042 0.03 0.3 0.22
0.03 0.07 0.033 0.02 0.43 0.19
0.03 0.059 0.033 0.04 0.44 0.13
0.03 0.069 0.071 0.04 0.32 0.32
0.03 0.069 0.04 0.03 0.38 0.3
0.03 0.067 0.027 0.03 0.38 0.11
0.03 0.074 0.03 0.03 0.36 0.12
0.03 0.073 0.036 0.03 0.34 0.24
0.01 0.037 0.014 0.01 0.15 0.08


In [ ]:
$\wprp$   & 0.17 & 0.475 & 0.031 & 0.03 & 0.78 & 0.45 \\
$\Dsigma$ & 0.06 & 0.149 & 0.081 & 0.07 & 0.86 & 0.43 \\
$\VPF$    & 0.10 & 0.155 & 0.783 & 0.21 & 0.56 & 2.73 \\
$\Pncic$  & 0.09 & 0.157 & 0.081 & 0.11 & 1.32 & 0.16 \\
$\Pncia$  & 0.04 & 0.137 & 0.088 & 0.11 & 0.91 & 0.33 \\
$\Pratio$ & 0.05 & 0.112 & 0.064 & 0.05 & 0.80 & 0.32 \\
$\wprp+\Dsigma$   & 0.05 & 0.123 & 0.024 & 0.02 & 0.53 & 0.29 \\
$\wprp+\VPF$      & 0.03 & 0.082 & 0.024 & 0.02 & 0.39 & 0.32 \\
$\wprp+\Pncic$    & 0.03 & 0.062 & 0.020 & 0.01 & 0.25 & 0.12 \\
$\wprp+\Pncia$    & 0.04 & 0.100 & 0.021 & 0.02 & 0.26 & 0.22 \\
$\wprp+\Pratio$   & 0.03 & 0.069 & 0.021 & 0.02 & 0.41 & 0.19 \\
$\Dsigma+\VPF$    & 0.04 & 0.083 & 0.054 & 0.04 & 0.39 & 0.25 \\
$\Dsigma+\Pncic$  & 0.03 & 0.065 & 0.031 & 0.02 & 0.30 & 0.12 \\
$\Dsigma+\Pncia$  & 0.03 & 0.076 & 0.042 & 0.03 & 0.30 & 0.22 \\
$\Dsigma+\Pratio$ & 0.03 & 0.070 & 0.033 & 0.02 & 0.43 & 0.19 \\
$\VPF+\Pncic$     & 0.03 & 0.059 & 0.033 & 0.04 & 0.44 & 0.13 \\
$\VPF+\Pncia$     & 0.03 & 0.069 & 0.071 & 0.04 & 0.32 & 0.32 \\
$\VPF+\Pratio$    & 0.03 & 0.069 & 0.040 & 0.03 & 0.38 & 0.30 \\
$\Pncic+\Pncia$   & 0.03 & 0.067 & 0.027 & 0.03 & 0.38 & 0.11 \\
$\Pncic+\Pratio$  & 0.03 & 0.074 & 0.030 & 0.03 & 0.36 & 0.12 \\
$\Pncia+\Pratio$  & 0.03 & 0.073 & 0.036 & 0.03 & 0.34 & 0.24 \\
$\wprp+\Dsigma+\VPF+\Pncic+\Pncia+\Pratio$ & 0.01 & 0.037 & 0.014 & 0.01 & 0.15 & 0.08 \\

In [31]:
for k in klist_all[:21]:
    #print k
    print np.round(sigma_tm_20p5[k][3],2),np.round(sigma_tm_20p5[k][2],3),\
    np.round(sigma_tm_20p5[k][0],3),np.round(sigma_tm_20p5[k][1],2),\
    np.round(sigma_tm_20p5[k][4],2),np.round(sigma_tm_20p5[k][5],2)
k = 'wdvcar'
print np.round(sigma_tm_20p5[k][3],2),np.round(sigma_tm_20p5[k][2],3),\
    np.round(sigma_tm_20p5[k][0],3),np.round(sigma_tm_20p5[k][1],2),\
    np.round(sigma_tm_20p5[k][4],2),np.round(sigma_tm_20p5[k][5],2)

0.05 0.244 0.038 0.03 1.07 0.6
0.05 0.197 0.098 0.06 1.05 0.52
0.07 0.117 1.023 0.11 0.71 2.57
0.07 0.282 0.07 0.06 1.53 0.25
0.04 0.209 0.126 0.12 1.88 0.4
0.04 0.186 0.06 0.03 1.42 0.41
0.03 0.132 0.036 0.02 0.7 0.34
0.02 0.084 0.034 0.02 0.53 0.45
0.03 0.148 0.031 0.02 0.6 0.19
0.03 0.136 0.03 0.02 0.6 0.3
0.03 0.134 0.029 0.02 0.79 0.25
0.03 0.083 0.065 0.03 0.51 0.32
0.04 0.14 0.039 0.02 0.57 0.2
0.02 0.106 0.054 0.03 0.53 0.27
0.03 0.118 0.039 0.02 0.67 0.24
0.02 0.084 0.036 0.03 0.6 0.22
0.02 0.083 0.073 0.03 0.53 0.37
0.02 0.088 0.042 0.03 0.58 0.38
0.03 0.13 0.034 0.03 0.78 0.18
0.03 0.142 0.037 0.02 0.87 0.2
0.03 0.125 0.042 0.03 0.77 0.27
0.01 0.052 0.02 0.01 0.29 0.11


In [ ]:
$\wprp$   & 0.05 & 0.244 & 0.038 & 0.03 & 1.07 & 0.60 \\
$\Dsigma$ & 0.05 & 0.197 & 0.098 & 0.06 & 1.05 & 0.52 \\
$\VPF$    & 0.07 & 0.117 & 1.023 & 0.11 & 0.71 & 2.57 \\
$\Pncic$  & 0.07 & 0.282 & 0.070 & 0.06 & 1.53 & 0.25 \\
$\Pncia$  & 0.04 & 0.209 & 0.126 & 0.12 & 1.88 & 0.40 \\
$\Pratio$ & 0.04 & 0.186 & 0.060 & 0.03 & 1.42 & 0.41 \\
$\wprp+\Dsigma$   & 0.03 & 0.132 & 0.036 & 0.02 & 0.70 & 0.34 \\
$\wprp+\VPF$      & 0.02 & 0.084 & 0.034 & 0.02 & 0.53 & 0.45 \\
$\wprp+\Pncic$    & 0.03 & 0.148 & 0.031 & 0.02 & 0.60 & 0.19 \\
$\wprp+\Pncia$    & 0.03 & 0.136 & 0.030 & 0.02 & 0.60 & 0.30 \\
$\wprp+\Pratio$   & 0.03 & 0.134 & 0.029 & 0.02 & 0.79 & 0.25 \\
$\Dsigma+\VPF$    & 0.03 & 0.083 & 0.065 & 0.03 & 0.51 & 0.32 \\
$\Dsigma+\Pncic$  & 0.04 & 0.140 & 0.039 & 0.02 & 0.57 & 0.20 \\
$\Dsigma+\Pncia$  & 0.02 & 0.106 & 0.054 & 0.03 & 0.53 & 0.27 \\
$\Dsigma+\Pratio$ & 0.03 & 0.118 & 0.039 & 0.02 & 0.67 & 0.24 \\
$\VPF+\Pncic$     & 0.02 & 0.084 & 0.036 & 0.03 & 0.60 & 0.22 \\
$\VPF+\Pncia$     & 0.02 & 0.083 & 0.073 & 0.03 & 0.53 & 0.37 \\
$\VPF+\Pratio$    & 0.02 & 0.088 & 0.042 & 0.03 & 0.58 & 0.38 \\
$\Pncic+\Pncia$   & 0.03 & 0.130 & 0.034 & 0.03 & 0.78 & 0.18 \\
$\Pncic+\Pratio$  & 0.03 & 0.142 & 0.037 & 0.02 & 0.87 & 0.20 \\
$\Pncia+\Pratio$  & 0.03 & 0.125 & 0.042 & 0.03 & 0.77 & 0.27 \\
$\wprp+\Dsigma+\VPF+\Pncic+\Pncia+\Pratio$ & 0.01 & 0.052 & 0.020 & 0.01 & 0.29 & 0.11 \\

In [32]:
for k in klist_all[:21]:
    #print k
    print np.round(sigma_tm_21p0[k][3],2),np.round(sigma_tm_21p0[k][2],3),\
    np.round(sigma_tm_21p0[k][0],3),np.round(sigma_tm_21p0[k][1],2),\
    np.round(sigma_tm_21p0[k][4],2),np.round(sigma_tm_21p0[k][5],2)
k = 'wdvcar'
print np.round(sigma_tm_21p0[k][3],2),np.round(sigma_tm_21p0[k][2],3),\
    np.round(sigma_tm_21p0[k][0],3),np.round(sigma_tm_21p0[k][1],2),\
    np.round(sigma_tm_21p0[k][4],2),np.round(sigma_tm_21p0[k][5],2)

0.19 0.308 0.097 0.03 0.84 0.9
0.08 0.101 0.228 0.07 0.67 0.81
0.12 0.149 1.558 0.1 0.53 4.1
0.19 0.273 0.148 0.11 2.46 0.36
0.06 0.07 0.277 0.15 1.48 0.88
0.05 0.081 0.091 0.03 0.8 0.62
0.05 0.074 0.081 0.02 0.38 0.57
0.05 0.073 0.084 0.03 0.41 0.7
0.06 0.083 0.065 0.02 0.56 0.26
0.04 0.061 0.076 0.02 0.4 0.5
0.04 0.068 0.063 0.02 0.49 0.37
0.05 0.062 0.159 0.04 0.36 0.56
0.05 0.064 0.073 0.02 0.41 0.3
0.03 0.044 0.119 0.03 0.3 0.47
0.04 0.055 0.077 0.02 0.37 0.41
0.06 0.082 0.073 0.03 0.51 0.3
0.04 0.059 0.205 0.04 0.38 0.78
0.05 0.067 0.083 0.03 0.4 0.57
0.04 0.064 0.062 0.03 0.61 0.25
0.05 0.072 0.065 0.03 0.68 0.27
0.04 0.06 0.077 0.03 0.52 0.42
0.02 0.03 0.042 0.01 0.21 0.18


In [ ]:
$\wprp$   & 0.19 & 0.308 & 0.097 & 0.03 & 0.84 & 0.90 \\
$\Dsigma$ & 0.08 & 0.101 & 0.228 & 0.07 & 0.67 & 0.81 \\
$\VPF$    & 0.12 & 0.149 & 1.558 & 0.10 & 0.53 & 4.10 \\
$\Pncic$  & 0.19 & 0.273 & 0.148 & 0.11 & 2.46 & 0.36 \\
$\Pncia$  & 0.06 & 0.070 & 0.277 & 0.15 & 1.48 & 0.88 \\
$\Pratio$ & 0.05 & 0.081 & 0.091 & 0.03 & 0.80 & 0.62 \\
$\wprp+\Dsigma$   & 0.05 & 0.074 & 0.081 & 0.02 & 0.38 & 0.57 \\
$\wprp+\VPF$      & 0.05 & 0.073 & 0.084 & 0.03 & 0.41 & 0.70 \\
$\wprp+\Pncic$    & 0.06 & 0.083 & 0.065 & 0.02 & 0.56 & 0.26 \\
$\wprp+\Pncia$    & 0.04 & 0.061 & 0.076 & 0.02 & 0.40 & 0.50 \\
$\wprp+\Pratio$   & 0.04 & 0.068 & 0.063 & 0.02 & 0.49 & 0.37 \\
$\Dsigma+\VPF$    & 0.05 & 0.062 & 0.159 & 0.04 & 0.36 & 0.56 \\
$\Dsigma+\Pncic$  & 0.05 & 0.064 & 0.073 & 0.02 & 0.41 & 0.30 \\
$\Dsigma+\Pncia$  & 0.03 & 0.044 & 0.119 & 0.03 & 0.30 & 0.47 \\
$\Dsigma+\Pratio$ & 0.04 & 0.055 & 0.077 & 0.02 & 0.37 & 0.41 \\
$\VPF+\Pncic$     & 0.06 & 0.082 & 0.073 & 0.03 & 0.51 & 0.30 \\
$\VPF+\Pncia$     & 0.04 & 0.059 & 0.205 & 0.04 & 0.38 & 0.78 \\
$\VPF+\Pratio$    & 0.05 & 0.067 & 0.083 & 0.03 & 0.40 & 0.57 \\
$\Pncic+\Pncia$   & 0.04 & 0.064 & 0.062 & 0.03 & 0.61 & 0.25 \\
$\Pncic+\Pratio$  & 0.05 & 0.072 & 0.065 & 0.03 & 0.68 & 0.27 \\
$\Pncia+\Pratio$  & 0.04 & 0.060 & 0.077 & 0.03 & 0.52 & 0.42 \\
$\wprp+\Dsigma+\VPF+\Pncic+\Pncia+\Pratio$ & 0.02 & 0.030 & 0.042 & 0.01 & 0.21 & 0.18 \\

In [ ]:
$\wprp$   &  
$\Dsigma$ &
$\VPF$    &
$\Pncic$  &
$\Pncia$  &
$\Pratio$ &
$\wprp+\Dsigma$   &
$\wprp+\VPF$      &
$\wprp+\Pncic$    & 
$\wprp+\Pncia$    & 
$\wprp+\Pratio$   &
$\Dsigma+\VPF$    & 
$\Dsigma+\Pncic$  &
$\Dsigma+\Pncia$  &
$\Dsigma+\Pratio$ &
$\VPF+\Pncic$     &
$\VPF+\Pncia$     &
$\VPF+\Pratio$    &
$\Pncic+\Pncia$   &
$\Pncic+\Pratio$  & 
$\Pncia+\Pratio$  &
$\wprp+\Dsigma+\VPF+\Pncic+\Pncia+\Pratio$ &